### PR TITLE
Update to Swift 4.2

### PR DESCRIPTION
**Pull request by snowzurfer**

### CODE REVIEW

**Comment by opalorange** [comment]
@snowzurfer Can you change the `.swift-version` file to `4.2` please and the `podspec` line `s.pod_target_xcconfig =  { 'SWIFT_VERSION' => '4.0' }`

**Comment by snowzurfer** [comment]
@opalorange np, there you go

**Comment by snowzurfer** [comment]
@opalorange want me to squash the commits into one?

**Comment by opalorange** [comment]
No need to do that

**Comment by opalorange** [comment]
@snowzurfer This is released 2.0.0

**Pull request merged**
